/* viora-allow-file: rule catalogue. Every "before" example is a deliberate
   violation, quoted on purpose so a model can recognise it in its own output. */

/* [why, fix, before, after] for every rule id in check.mjs --list-rules */
export const CHECK = {
	"em-dash": [
		"Nothing else in a generated page is as recognisable. People reach for a comma; the long dash is a model habit.",
		"Comma, colon or period. An en dash only between numbers.",
		"Fast, reliable \u2014 and built for teams",
		"Fast, reliable, and built for teams",
	],
	lorem: [
		"Placeholder latin hides the fact that the layout was never tested against real sentence length.",
		"Write the real sentence, even a rough one. Real copy changes the layout.",
		"<p>Lorem ipsum dolor sit amet consectetur</p>",
		"<p>Halyard drafts the note the moment the pull request merges.</p>",
	],
	"slop-names": [
		"Acme, John Doe and Jane Smith tell the reader that nobody ever used this screen.",
		"Plausible names matched to the audience and the locale.",
		"John Doe, Acme Inc.",
		"Marta Sundqvist, Kvartal",
	],
	"fake-stat": [
		"A perfect number with no source reads as decoration, and it makes the real numbers look invented too.",
		"Use a measured figure with a source line, or drop the claim.",
		"10x faster releases",
		"Median draft time 3 min. Our telemetry, 12 months, 340 workspaces.",
	],
	"filler-words": [
		"Seamless, powerful, robust, cutting-edge: words that survive any product and inform nobody.",
		"Replace with the mechanism, the number or the limit.",
		"A powerful, seamless release workflow",
		"Two approvals publish it. One rejection sends it back with the reason.",
	],
	"scroll-cue": [
		"A bouncing arrow teaches nothing. If the page looks scrollable, it is.",
		"Delete it. Let the first viewport cut a line of content so the page reads as continuing.",
		'<div class="scroll-hint">Scroll to explore</div>',
		"<!-- nothing. The next section starts 40px below the fold -->",
	],
	"section-number": [
		"01 / 02 / 03 above headings is a template tic implying an order the page does not have.",
		"Let type scale and space carry hierarchy. Numbers only for real progress.",
		"<span>01</span><h2>Features</h2>",
		"<h2>Three jobs, one pass</h2>",
	],
	eyebrow: [
		"The small tracked uppercase label above a heading is the most common generated pattern there is.",
		"Fold the context into the heading itself.",
		'<p class="eyebrow">WHY HALYARD</p><h2>Built for teams</h2>',
		"<h2>Why teams keep Halyard after the trial</h2>",
	],
	"gradient-text": [
		"Clipping a gradient into a heading dates the work to 2021 and breaks selection and contrast.",
		"Solid ink. Carry emphasis with weight, size or one accent word.",
		"background: linear-gradient(90deg,#6366f1,#ec4899); -webkit-background-clip: text",
		"color: var(--ink); font-weight: var(--weight-display)",
	],
	"neon-glow": [
		"A shadow with no offset is a halo. Light comes from somewhere; a halo comes from nowhere.",
		"Offset plus blur, tinted from the ink hue.",
		"box-shadow: 0 0 24px rgba(99,102,241,.6)",
		"box-shadow: 0 8px 24px hsl(var(--shadow-hsl) / .12)",
	],
	"unsplash-hotlink": [
		"A hotlinked stock photo rots, slows the page, and is always the same photo everyone else used.",
		"Local asset, or a documented placeholder that the report flags as one.",
		'<img src="https://images.unsplash.com/photo-1521">',
		'<img src="/img/console-1280.png" width="1280" height="860" alt="Draft view">',
	],
	"banned-font": [
		"Inter, Roboto, Poppins, Montserrat are defaults, not decisions. Nothing is wrong with them except that nobody chose them.",
		"Pin a face for a reason and write the reason in one line, or take a pair from data/type-pairs.csv.",
		"font-family: Poppins, sans-serif",
		"font-family: var(--font-display) /* Fraunces: editorial voice, ships Cyrillic */",
	],
	"tiny-text": [
		"Under 12px nobody reads. Between 12 and 16 only labels belong.",
		"Body 16px, labels 13 to 14, nothing under 12.",
		"font-size: 10px",
		"font-size: var(--text-sm)",
	],
	"transition-all": [
		"It animates properties you never intended, including layout, and turns every later change into a bug.",
		"Name each property.",
		"transition: all .2s ease",
		"transition: background-color var(--dur-fast) var(--ease-out)",
	],
	"scale-zero": [
		"Material appearing from nothing is a machine effect. Real things enter from close by.",
		"scale(.96) to scale(1), with opacity.",
		"from { transform: scale(0) }",
		"from { transform: scale(.96); opacity: 0 }",
	],
	"ease-in-enter": [
		"ease-in starts slow, which reads as lag on anything the person just triggered.",
		"ease-out for entrances. ease-in is for exits.",
		"transition: opacity .2s ease-in",
		"transition: opacity var(--dur-fast) var(--ease-out)",
	],
	"transition-layout": [
		"Animating width, height, top or margin runs layout on every frame.",
		"Animate transform and opacity. interpolate-size for height.",
		"transition: height .3s ease",
		"transition: transform var(--dur-base) var(--ease-out)",
	],
	"slow-motion": [
		"Over 300ms an in-app transition feels like waiting for the interface to agree with you.",
		"In-app motion caps at 300ms. Page level, 500ms.",
		"transition: transform .8s",
		"transition: transform var(--dur-base) var(--ease-out)",
	],
	"scroll-listener": [
		"A scroll handler that writes styles runs on the main thread and stutters on the first slow frame.",
		"CSS animation-timeline: view(), or IntersectionObserver.",
		'window.addEventListener("scroll", () => { el.style.opacity = y / 400 })',
		"animation-timeline: view(); animation-range: entry 0% cover 30%",
	],
	"motion-axis-keys": [
		"Separate x and y keys interpolate independently, so the element wobbles on its way in.",
		"Write the whole transform as one value.",
		"{ x: [0, 20], y: [0, 8] }",
		"transform: translate3d(0,0,0) to translate3d(20px,8px,0)",
	],
	"hover-ungated": [
		"On a touch screen a hover style fires on tap and sticks until the person taps somewhere else.",
		"Wrap hover rules in @media (hover: hover).",
		".card:hover { transform: translateY(-4px) }",
		"@media (hover: hover) { .card:hover { transform: translateY(-4px) } }",
	],
	"pure-black-text": [
		"Maximum black on white vibrates, and on OLED it looks cheap.",
		"Near-black ink from the palette.",
		"color: #000",
		"color: var(--ink)",
	],
	"raw-hex": [
		"A colour written inside a component is a colour nobody can change. The palette stops being a palette.",
		"Declare it once as a custom property, then reference the token.",
		"background: #1d4ed8",
		"background: var(--accent)",
	],
	important: [
		"It means the cascade is already wrong, and the next override will need two of them.",
		"Fix specificity, or move the rule next to the component.",
		"color: red !important",
		'[data-state="error"] .field { color: var(--danger) }',
	],
	"zindex-high": [
		"9999 is a guess that wins today and loses next week.",
		"Five steps in tokens: --z-1 through --z-5.",
		"z-index: 9999",
		"z-index: var(--z-4)",
	],
	"vh-height": [
		"On mobile 100vh is taller than the visible area, so the hero hides its own button under the browser chrome.",
		"100dvh, or let the content set the height.",
		"min-height: 100vh",
		"min-height: 100dvh",
	],
	"focus-none": [
		"Removing the outline with nothing in its place makes the interface unusable from a keyboard.",
		"Replace it with a :focus-visible ring built from the --focus token.",
		"*:focus { outline: none }",
		":focus-visible { outline: var(--focus); outline-offset: 2px }",
	],
	"img-no-alt": [
		"A missing alt is read aloud as the file name.",
		'Describe what the image shows, or alt="" if it is truly decorative.',
		'<img src="/hero.png">',
		'<img src="/hero.png" alt="Merged pull requests left, the draft note right">',
	],
	"viewport-no-zoom": [
		"Blocking zoom takes the page away from the people who need it most.",
		"width=device-width, initial-scale=1, and nothing else.",
		'<meta name="viewport" content="width=device-width, maximum-scale=1">',
		'<meta name="viewport" content="width=device-width, initial-scale=1">',
	],
	"tabindex-positive": [
		"A positive tabindex jumps ahead of everything else and breaks the reading order for everyone.",
		"Use 0 or -1 and fix the DOM order instead.",
		'<div tabindex="3">',
		'<button type="button"> placed where it reads',
	],
	"icon-button-unnamed": [
		'An icon-only button with no name is announced as "button".',
		"aria-label, or visually hidden text.",
		"<button><svg /></button>",
		'<button type="button" aria-label="Dismiss"><svg aria-hidden="true" /></button>',
	],
	"emoji-icon": [
		"Emoji render differently on every platform and read as chat, not product.",
		"One real icon set at one stroke weight.",
		"<span>\u{1F680}</span> Launch",
		'<svg aria-hidden="true" stroke-width="1.75">...</svg> Launch',
	],
	"poetic-label": [
		"Crafted with care, thoughtfully engineered: performance of craft instead of craft.",
		"Say the functional thing, or say nothing.",
		"Thoughtfully crafted for modern teams",
		"Two approvals, then it publishes",
	],
	"middle-dot-strip": [
		"Metadata glued together with middle dots is a template pattern, and unreadable at 320px.",
		"One separator per line. Then space, hairlines or columns.",
		"12 min read \u00b7 26 Aug \u00b7 Design \u00b7 EN",
		"<time>26 Aug</time> in Design, 12 min",
	],
	"locale-strip": [
		"A time and weather line in a product UI is decoration pretending to be information.",
		"Show it only if somebody acts on it.",
		"Astrakhan 14:32, cloudy",
		"<!-- removed. Nobody schedules a release by the weather -->",
	],
	"version-stamp": [
		"A version chip in a hero is set dressing borrowed from developer tools.",
		"Ship it only when the release state is the message.",
		"<span>v2.4.1</span>",
		'<a href="/changelog">What shipped in August</a>',
	],
	"pure-black-surface": [
		"A pure black ground kills every shadow and every edge, so depth disappears.",
		"Use the palette's darkest surface.",
		"background: #000",
		"background: var(--canvas)",
	],
	"image-hover": [
		"An image is not an action target, so hovering the picture instead of the card confuses what is clickable.",
		"Move the feedback to the container.",
		".card img:hover { transform: scale(1.05) }",
		"@media (hover: hover) { .card:hover { border-color: var(--accent-line) } }",
	],
	"placeholder-as-label": [
		"The placeholder disappears exactly when the person needs to check what they are filling in.",
		"A real label. Placeholder for format only.",
		'<input placeholder="Email">',
		'<label for="email">Email</label><input id="email" placeholder="you@company.com">',
	],
	"h1-multiple": [
		"Two tops is no top. Screen readers and search read the outline literally.",
		"One h1 per document.",
		"<h1>Halyard</h1> ... <h1>Pricing</h1>",
		"<h1>Halyard</h1> ... <h2>Pricing</h2>",
	],
	"heading-skip": [
		"Jumping from h2 to h4 breaks the outline that assistive tech reads, whatever the font sizes look like.",
		"Step one level at a time and style with tokens, not tags.",
		"<h2>Pricing</h2><h4>Team</h4>",
		'<h2>Pricing</h2><h3 class="m-price-title">Team</h3>',
	],
	"html-lang-missing": [
		"Without lang the reader guesses the voice, and hyphenation and quote marks follow the wrong locale.",
		"Set it on the html element.",
		"<html>",
		'<html lang="ru">',
	],
	"lang-copy-mismatch": [
		"Declaring English over Cyrillic copy gives the wrong voice, hyphenation and quotes.",
		"Declare the language the page actually speaks.",
		'<html lang="en"> ... \u041e\u0442\u0447\u0451\u0442\u044b \u043f\u043e \u0440\u0435\u043b\u0438\u0437\u0430\u043c',
		'<html lang="ru"> ... \u041e\u0442\u0447\u0451\u0442\u044b \u043f\u043e \u0440\u0435\u043b\u0438\u0437\u0430\u043c',
	],
	"ai-gradient": [
		"Violet into blue is the default gradient of every generated page since 2022. It dates the work in one glance.",
		"One solid accent from the palette. If you need a field, use a very low contrast tint.",
		"background: linear-gradient(135deg,#6366f1,#a855f7)",
		"background: var(--surface); border: 1px solid var(--hairline)",
	],
	"framework-default-shadow": [
		"An untinted black shadow is the framework default and reads as grey fog under the card.",
		"Tint from the ink hue, and give it offset plus blur.",
		"box-shadow: 0 4px 6px rgba(0,0,0,.1)",
		"box-shadow: var(--shadow-2)",
	],
	"hero-mesh-blob": [
		"The blurred blob behind a hero is filler standing where an image, a screenshot or nothing should be.",
		"Real image, flat field, or nothing.",
		'<div class="blob" style="filter: blur(120px)"></div>',
		'<img src="/img/console-1280.png" width="1280" height="860" alt="Draft view">',
	],
	"center-everything": [
		"When every block is centred nothing has an edge to hold, and the page loses its spine.",
		"Centre the hero at most, then align one edge down the page.",
		"every section text-align: center",
		"hero centred, everything below aligned to the container start",
	],
	"card-monotony": [
		"Three identical hand-written cards read as a layout stub, not a system.",
		"Vary the family: one lead card then narrow ones, or hairline rows.",
		"three cards with identical markup and weight",
		"one wide lead card, two narrow ones beside it",
	],
	"div-click-target": [
		"A div with a click handler cannot be reached, focused or activated from a keyboard.",
		"Use a button, or add role, tabindex and key handling.",
		'<div onclick="open()">Open</div>',
		'<button type="button" onclick="open()">Open</button>',
	],
	"svg-unlabelled": [
		"An svg with no aria state is announced either as nothing or as junk.",
		"aria-hidden for decoration, a title or label for meaning.",
		"<svg><path d=... /></svg>",
		'<svg aria-hidden="true"><path d=... /></svg>',
	],
	"img-no-dimensions": [
		"Without width and height the layout jumps when the image lands. That jump is most of your CLS.",
		"Set width and height, or an aspect-ratio.",
		'<img src="/a.png" alt="Console">',
		'<img src="/a.png" alt="Console" width="1280" height="860">',
	],
	"overflow-x-hack": [
		"Hiding horizontal overflow hides a layout bug, and then hides the fix too.",
		"Find what overflows at 320px and fix that element.",
		"body { overflow-x: hidden }",
		"min-width: 0 on the flex child that was pushing",
	],
	"off-rhythm-space": [
		"A 13px gap is a value nobody chose, and a page of them has no rhythm.",
		"Use the space tokens. The base is 4px.",
		"margin-top: 13px",
		"margin-top: var(--space-4)",
	],
	"arbitrary-px-class": [
		"An arbitrary pixel class means the scale was abandoned mid-file.",
		"Add the step to the scale, or use the nearest existing one.",
		'class="mt-[13px]"',
		'class="mt-3"',
	],
	"display-no-tracking": [
		"Above roughly 40px, default tracking looks unset and the headline reads loose.",
		"letter-spacing between -0.02em and -0.04em on display sizes.",
		"font-size: 56px",
		"font-size: var(--text-display-2); letter-spacing: -.02em",
	],
	"title-case-heading": [
		"Title Case in an interface is deck voice, and it inflates every label.",
		"Sentence case everywhere except proper nouns.",
		"Start Your Free Trial",
		"Start your free trial",
	],
	"reduced-motion-missing": [
		"For some people motion causes nausea, not delight. Shipping animation without the query ships harm.",
		"Add prefers-reduced-motion in the same commit as the animation.",
		"animation everywhere, no query",
		"@media (prefers-reduced-motion: reduce) { *, *::before { animation-duration: 1ms; transition-duration: 1ms } }",
	],
	"marquee-multi": [
		"One scrolling row is a device. Two is a tic, and they fight each other for the eye.",
		"Keep one, delete the rest.",
		"logo marquee plus testimonial marquee",
		"static logo row, testimonials in a grid",
	],
	"focus-ring-missing": [
		"No :focus-visible anywhere means keyboard users see nothing move as they navigate.",
		"One global focus-visible rule built from the --focus token.",
		"no focus styles in the project",
		":focus-visible { outline: var(--focus); outline-offset: 2px }",
	],
	"cyrillic-latin-face": [
		"A Latin-only face with Cyrillic copy falls back to a system font silently, and the design is gone.",
		"Pick a face that ships Cyrillic. data/cyrillic-pairs.csv has 26 tested pairs.",
		"font-family: Poppins /* \u041e\u0442\u0447\u0451\u0442\u044b */",
		"font-family: Onest, system-ui /* ships Cyrillic */",
	],
	"hue-count": [
		"Three or more chromatic families plus semantics makes a page that cannot decide what matters.",
		"Neutrals plus two colours, maximum.",
		"blue, violet, teal and orange accents in one view",
		"graphite neutrals, one blue accent, semantic colours only for state",
	],
	"radius-family": [
		"Mixed radii read as parts from different kits.",
		"One radius family in tokens: sm, md, lg.",
		"border-radius: 4px, 10px and 18px in one view",
		"var(--radius-sm) / var(--radius-md) / var(--radius-lg)",
	],
	"font-count": [
		"Four families is a font sample, not a design.",
		"Display, text, mono. Three is the ceiling.",
		"Inter, Poppins, Playfair and Roboto Mono",
		"var(--font-display), var(--font-text), var(--font-mono)",
	],
	"icon-stroke-mixed": [
		"Two stroke weights in one icon set reads as borrowed icons.",
		"One weight everywhere, usually 1.5 or 1.75.",
		'stroke-width="1.5" and stroke-width="2" in one view',
		'stroke-width="1.75" everywhere',
	],
	"glass-overuse": [
		"Glass on every surface removes the contrast that made the first glass surface interesting.",
		"One glass layer. Two at the very most.",
		"backdrop-filter on header, cards, modal and sidebar",
		"backdrop-filter on the sticky header only",
	],
	"tokens-missing": [
		"Without a token layer every change is a search and replace, and no two components agree.",
		"One token file, referenced everywhere. Lint a fragment together with tokens.css.",
		"colours and sizes written per component",
		":root { --canvas: ...; --ink: ... } then var(--ink) everywhere",
	],
}
