/* viora-allow-file: rule catalogue. Every "before" example is a deliberate
   violation, quoted on purpose so a model can recognise it in its own output. */

/* [why, fix, before, after] for every rule id in wig.mjs --list-rules */
export const WIG = {
	"paste-blocked": [
		"Blocking paste breaks password managers and makes a long token impossible to enter correctly.",
		"Never block paste. Validate after the value arrives.",
		"onPaste={(event) => event.preventDefault()}",
		"<input onChange={...} /> plus validation on submit",
	],
	"zoom-blocked": [
		"user-scalable=no removes pinch zoom from the people who need it most.",
		"width=device-width, initial-scale=1, nothing else.",
		'content="width=device-width, user-scalable=no"',
		'content="width=device-width, initial-scale=1"',
	],
	"value-no-onchange": [
		"value without onChange makes a field that looks editable and refuses every keystroke.",
		"Add onChange, or use defaultValue for an uncontrolled field.",
		"<input value={name} />",
		"<input value={name} onChange={(e) => setName(e.target.value)} />",
	],
	"autocomplete-missing": [
		"Without autocomplete the browser cannot fill a form a person fills twenty times a year.",
		"Set the right token: email, name, organization, or off for secrets.",
		'<input name="email">',
		'<input name="email" autocomplete="email">',
	],
	"spellcheck-on-token": [
		"Red squiggles under an API key or an email make a correct value look wrong.",
		"spellcheck=false on codes, tokens, emails and URLs.",
		'<input name="token">',
		'<input name="token" autocomplete="off" spellcheck={false}>',
	],
	"submit-gated": [
		"A disabled submit hides the reason, so the person cannot ask the form what is wrong.",
		"Keep it enabled, validate on submit, focus the first bad field.",
		"<button disabled={!valid}>Save</button>",
		'<button type="submit">Save</button> plus an error beside the field',
	],
	"button-no-type": [
		"Inside a form a button without type submits it, so Cancel can save the record.",
		"type=button unless it really submits.",
		"<button onClick={cancel}>Cancel</button>",
		'<button type="button" onClick={cancel}>Cancel</button>',
	],
	"link-no-href": [
		"An anchor with only a click handler is not focusable and cannot be opened in a new tab.",
		"Give it an href, or make it a button.",
		"<a onClick={go}>Releases</a>",
		'<a href="/releases">Releases</a>',
	],
	"link-hash-onclick": [
		"href=# scrolls to the top and lies about being a link.",
		"Use a button for actions.",
		'<a href="#" onClick={open}>Open</a>',
		'<button type="button" onClick={open}>Open</button>',
	],
	"iframe-no-title": [
		'An unnamed iframe is announced as "frame" and nothing else.',
		"Add a title that says what is inside.",
		'<iframe src="/demo">',
		'<iframe src="/demo" title="Release demo">',
	],
	autofocus: [
		"Autofocus on mobile opens the keyboard over the content and skips the context above the field.",
		"Focus after an explicit action, and on desktop only.",
		"<input autoFocus>",
		"focus in the handler that opens the dialog",
	],
	"three-periods": [
		"Three periods are three characters that never kern. The ellipsis is one character.",
		"Use the ellipsis character.",
		"Saving...",
		"Saving\u2026",
	],
	"loading-no-ellipsis": [
		"A progress label with no trailing ellipsis reads as a finished state.",
		"Saving, then the past tense when it lands.",
		"Saving",
		"Saving\u2026 then Saved",
	],
	"nbsp-units": [
		"A number can end a line and leave its unit stranded on the next one.",
		"Non-breaking space between the value and the unit.",
		"5 000 \u20bd",
		"5&nbsp;000&nbsp;\u20bd",
	],
	"flex-truncate-minw": [
		"text-overflow does nothing inside a flex child until min-width is 0.",
		"Add min-width: 0, or min-w-0 in Tailwind.",
		"display:flex with overflow:hidden and text-overflow:ellipsis",
		"the same, plus min-width: 0 on the truncating child",
	],
	"hand-date": [
		"Hand-built dates get the locale, the separator and the timezone wrong, and server and client disagree.",
		"Intl.DateTimeFormat, built once at module scope.",
		"`${d.getDate()}.${d.getMonth() + 1}.${d.getFullYear()}`",
		"const day = new Intl.DateTimeFormat(locale, opts) then day.format(d)",
	],
	"hand-number": [
		"Manual thousands separators and currency symbols break in every other locale.",
		"Intl.NumberFormat, built once at module scope.",
		'"$" + n.toFixed(2)',
		"const money = new Intl.NumberFormat(locale, { style: 'currency', currency }) then money.format(n)",
	],
	"lazy-priority-conflict": [
		"lazy plus high priority tells the browser two opposite things, and the hero image loses the race.",
		"Hero: eager and high. Below the fold: lazy.",
		'<img loading="lazy" fetchpriority="high">',
		'<img loading="eager" fetchpriority="high" decoding="async">',
	],
	"gif-media": [
		"An animated gif is ten times the bytes of the same video and cannot be paused.",
		"Muted looping video, or a still with a play control.",
		'<img src="demo.gif">',
		"<video src=\"demo.mp4\" muted loop playsinline>",
	],
	"layout-read": [
		"Reading offsetHeight during render forces a synchronous layout on every pass.",
		"Read in an effect or a handler, or use ResizeObserver.",
		"const h = el.offsetHeight // in render",
		"useEffect(() => setH(el.offsetHeight), [])",
	],
	"random-in-render": [
		"Math.random in render gives the server one value and the client another, so React throws the markup away.",
		"A counter, a stable id from useId, or a value from the server.",
		"key={Math.random()}",
		"key={note.id} / const id = useId()",
	],
	"date-in-render": [
		"new Date() in render hydrates with two different times.",
		"Pass the timestamp in as a prop and format it with Intl.",
		"<span>{new Date().toLocaleString()}</span>",
		"<time dateTime={iso}>{day.format(new Date(iso))}</time>",
	],
	"destructive-bare": [
		"Delete with no confirmation and no undo means one mis-tap loses work.",
		"Typed confirmation for the irreversible, undo for everything else.",
		"<button onClick={remove}>Delete</button>",
		"a confirm dialog that wants the workspace name typed, or an undo toast",
	],
	"url-state": [
		"Tab, filter, sort and query in useState cannot be linked, bookmarked or reloaded.",
		"Shareable state in the URL. useState for transient state only.",
		'const [tab, setTab] = useState("open")',
		'const [tab, setTab] = useUrlState("tab", "open")',
	],
	"overscroll-missing": [
		"Scrolling to the end of a drawer starts scrolling the page behind it.",
		"overscroll-behavior: contain on the scroll container.",
		".drawer { overflow-y: auto }",
		".drawer { overflow-y: auto; overscroll-behavior: contain }",
	],
	"color-scheme-missing": [
		"Without color-scheme the native scrollbars, form controls and autofill stay light on a dark page.",
		"color-scheme on :root.",
		"dark tokens and nothing else",
		":root { color-scheme: light dark }",
	],
	"safe-area-missing": [
		"A fixed bar sits under the home indicator on a phone.",
		"Add env(safe-area-inset-*) to the padding.",
		"position: fixed; bottom: 16px",
		"bottom: calc(var(--space-4) + env(safe-area-inset-bottom))",
	],
	"touch-action-missing": [
		"Without touch-action: manipulation a tap waits for a possible double tap before it fires.",
		"Set it on interactive elements.",
		"button { }",
		"button { touch-action: manipulation }",
	],
	"text-wrap-missing": [
		"A heading that drops one word onto the last line looks broken, and it happens at every width you did not test.",
		"text-wrap: balance on headings, pretty on body copy.",
		"h1 { font-size: var(--text-h1) }",
		"h1 { font-size: var(--text-h1); text-wrap: balance }",
	],
	"font-display-missing": [
		"Without font-display the text is invisible while the font loads.",
		"font-display: swap.",
		"@font-face { src: url(a.woff2) }",
		"@font-face { src: url(a.woff2); font-display: swap }",
	],
	"preconnect-missing": [
		"A remote font costs a DNS lookup, a TCP handshake and a TLS handshake before the first byte arrives.",
		"preconnect to the font host, with crossorigin.",
		'<link href="https://fonts.googleapis.com/css2?..." rel="stylesheet">',
		'<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> then the stylesheet',
	],
	"theme-color-missing": [
		"The browser chrome stays white above a dark page, so the app looks pasted into the phone.",
		"Two theme-color metas, one per colour scheme.",
		"no theme-color at all",
		'<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#0b0b0d">',
	],
	"aria-live-missing": [
		"A toast or an inline result that appears with no live region is silent for a screen reader.",
		"role=status with aria-live=polite, rendered before the first message.",
		'<div class="toast">Saved</div>',
		'<div role="status" aria-live="polite">{message}</div>',
	],
	"escape-close-missing": [
		"An overlay that ignores Escape traps the keyboard inside it.",
		"Native dialog with showModal, or a keydown handler.",
		'<div class="modal">',
		"<dialog ref={ref} onCancel={close}>",
	],
	"drag-no-keyboard": [
		"Drag and drop with no keyboard path excludes anyone who cannot drag.",
		"Add move up and move down, or arrow-key reordering.",
		"onDragStart and nothing else",
		'drag plus <button type="button">Move up</button>',
	],
	"tabular-nums-missing": [
		"Proportional digits make columns jitter, so numbers cannot be compared down the column.",
		"font-variant-numeric: tabular-nums on numeric columns.",
		"<td>1,284</td>",
		'<td class="a-num">1,284</td> with tabular-nums',
	],
}
